"""empty message

Revision ID: 437077bef01d
Revises: 
Create Date: 2023-07-13 09:35:12.786590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437077bef01d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_habit_habit'), ['habit'], unique=False)
        batch_op.create_index(batch_op.f('ix_habit_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_status'))
        batch_op.drop_index(batch_op.f('ix_habit_habit'))
        batch_op.drop_index(batch_op.f('ix_habit_date'))

    op.drop_table('habit')
    # ### end Alembic commands ###
